"""
Enumerate BigQuery datasets, tables/views, and columns for Demografy.

Run from the Demografy folder (venv active; ``pip install -r requirements.txt``):

    python db/evaluate_bigquery_catalog.py
    python db/evaluate_bigquery_catalog.py --with-counts

Requires GOOGLE_APPLICATION_CREDENTIALS and BIGQUERY_PROJECT in .env.

Writes:
    db/bigquery_catalog_snapshot.json   — machine-readable (gitignored by ``*.json``)
    db/bigquery_catalog_snapshot.md     — review / diff-friendly tables

Use snapshots to plan richer SQL (joins, LGA names, benchmarks) in ``sql_agent`` / ``prompts``.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

# Demografy repo root (parent of ``db/``)
ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

JSON_OUT = ROOT / "db" / "bigquery_catalog_snapshot.json"
MD_OUT = ROOT / "db" / "bigquery_catalog_snapshot.md"


def _fetch_catalog(*, include_counts: bool) -> dict:
    from db.bigquery_client import get_client

    client = get_client()
    project = client.project

    snapshot: dict = {
        "project": project,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "datasets": [],
    }

    datasets = sorted(client.list_datasets(), key=lambda d: d.dataset_id)
    for ds in datasets:
        ds_id = ds.dataset_id
        ds_entry: dict = {
            "dataset_id": ds_id,
            "tables": [],
        }

        tables_sql = f"""
SELECT table_name, table_type
FROM `{project}.{ds_id}.INFORMATION_SCHEMA.TABLES`
WHERE table_type IN ('BASE TABLE', 'VIEW')
ORDER BY table_name
"""
        tjob = client.query(tables_sql)
        table_rows = list(tjob.result())

        cols_sql = f"""
SELECT table_name, column_name, ordinal_position, data_type, is_nullable
FROM `{project}.{ds_id}.INFORMATION_SCHEMA.COLUMNS`
ORDER BY table_name, ordinal_position
"""
        cjob = client.query(cols_sql)
        col_rows = list(cjob.result())

        by_table: dict[str, dict] = {}
        for row in table_rows:
            by_table[row.table_name] = {
                "name": row.table_name,
                "type": row.table_type,
                "columns": [],
            }

        for row in col_rows:
            tname = row.table_name
            if tname not in by_table:
                continue
            by_table[tname]["columns"].append(
                {
                    "name": row.column_name,
                    "position": row.ordinal_position,
                    "data_type": row.data_type,
                    "nullable": row.is_nullable,
                }
            )

        for tname in sorted(by_table.keys()):
            info = by_table[tname]
            row_count = None
            if include_counts and info["type"] == "BASE TABLE":
                try:
                    cjob = client.query(
                        f"SELECT COUNT(*) AS n FROM `{project}.{ds_id}.{tname}`"
                    )
                    row_count = next(cjob.result()).n
                except Exception as exc:
                    row_count = f"error: {exc}"
            info["approx_row_count"] = row_count
            ds_entry["tables"].append(info)

        snapshot["datasets"].append(ds_entry)

    return snapshot


def _render_markdown(snapshot: dict) -> str:
    lines: list[str] = []
    lines.append("# BigQuery catalog snapshot")
    lines.append("")
    lines.append(f"- **Project:** `{snapshot['project']}`")
    lines.append(f"- **Generated (UTC):** {snapshot['generated_at_utc']}")
    lines.append("")
    lines.append(
        "This file is generated by `db/evaluate_bigquery_catalog.py`. "
        "Use it to compare **prod_tables** vs **ref_tables** and plan richer answers "
        "(join keys, extra dimensions, benchmarks)."
    )
    lines.append("")

    for ds in snapshot["datasets"]:
        lines.append(f"## Dataset `{ds['dataset_id']}`")
        lines.append("")
        for t in ds["tables"]:
            lines.append(f"### `{t['name']}` ({t['type']})")
            if t.get("approx_row_count") is not None:
                lines.append(f"- **Rows:** {t['approx_row_count']}")
            lines.append("")
            lines.append("| # | Column | Type | Nullable |")
            lines.append("|---|--------|------|----------|")
            for c in t["columns"]:
                lines.append(
                    f"| {c['position']} | `{c['name']}` | {c['data_type']} | {c['nullable']} |"
                )
            lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Snapshot BigQuery schema for Demografy.")
    parser.add_argument(
        "--with-counts",
        action="store_true",
        help="Run COUNT(*) per base table (slower; skips views).",
    )
    args = parser.parse_args()

    try:
        snapshot = _fetch_catalog(include_counts=args.with_counts)
    except Exception as exc:
        print(f"Catalog fetch failed: {exc}", file=sys.stderr)
        print(
            "Ensure .env has GOOGLE_APPLICATION_CREDENTIALS pointing to a valid JSON key "
            "and the service account can read BigQuery metadata.",
            file=sys.stderr,
        )
        return 1

    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps(snapshot, indent=2), encoding="utf-8")
    MD_OUT.write_text(_render_markdown(snapshot), encoding="utf-8")

    print(f"Wrote {JSON_OUT}")
    print(f"Wrote {MD_OUT}")

    # Compact stdout summary for CI / logs
    for ds in snapshot["datasets"]:
        n_tables = len(ds["tables"])
        print(f"  dataset {ds['dataset_id']}: {n_tables} tables/views")
    return 0


if __name__ == "__main__":
    sys.exit(main())
